### ISSUE TITLE
Create Github repository for the project

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#1]
The Democratic Republic of Congo need to have a dedicated github project for the MapStore framework to develop with MapStore and/or customize and maintain the MapStore instance autonomously if needed.

**Comment by chpicone** [comment]
/remind me to ask @tdipisa to the correctness of the repo on 6th July

**Comment by chpicone** [comment]
/remind me to ask @tdipisa to the correctness of the repo on 6th July

**Comment by tdipisa** [comment]
@chpicone you have already created the repo, I think this issue is useless. We just need to populate it (issue #2).

**Comment by chpicone** [comment]
@tdipisa I have created this issue to make you able to review the creation of the repo.
It was my first repo and I preferred to have a review from you.

**Comment by tdipisa** [comment]
@chpicone I see that this repo doesn't have its own workspace but it is using the DevOps one, why?

**Comment by chpicone** [comment]
@tdipisa because I saw the same thing for other projects (eg. [C098](https://github.com/geosolutions-it/MapStore2-C098/settings#workspaces), in this case using DevOps board).

**Comment by simboss** [comment]
@tdipisa this repo belongs to the mapstore workspace because this is a mapstore workspace.

We discussed this already and I documented in the PM guidelines. No more individual workspaces.

**Comment by tdipisa** [comment]
@simboss @chpicone I can only see **DevOps Board** as workspace and too many repositories connected here. @chpicone yes, the same is for C098 but I think it is a mistake.

**Comment by simboss** [comment]
shall be fixed now...
