### ISSUE TITLE
Create a Test instance of MapStore

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#12]
We need to prepare a TEST environment with the MapStore for the Congo project.

**Comment by randomorder** [comment]
@chpicone
I miss some infor about the VM. Can you please open an issue with the template provided here https://github.com/geosolutions-it/DevOps/issues/new/choose ?

**Comment by chpicone** [comment]
@randomorder [here](https://github.com/geosolutions-it/DevOps/issues/289) the issue.

**Comment by randomorder** [comment]
Thanks. Giacomo will start working on the creation of the VM straightaway

**Comment by randomorder** [comment]
@chpicone
Done. GDoc [here](https://docs.google.com/document/d/1F1YFqmNBx0KiM7g4oxm6kjs6nlTtOsISOSYT9VwweNY/edit#)
Moving to test
