### ISSUE TITLE
Create Jenkins Job for continous deploy

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#15]
We need to create a Jenkins Job to deploy MS in the Test Environment

**Comment by randomorder** [comment]
@MV88 I cloned MapStore2_Dev Build job and I am getting build errors:
https://build.geo-solutions.it/jenkins/view/FAO/job/FAO%20-%20MapStore/1/console
Can you take a look?

**Comment by randomorder** [comment]
MapStore build ok now. Moving on with deployment

**Comment by randomorder** [comment]
Done https://build.geo-solutions.it/jenkins/view/FAO/ . I am currently testing it.

**Comment by chpicone** [comment]
@randomorder the build yesterday failed. Please, can someone take a look?

```
Connecting to ms-congo.geo-solutions.it (ms-congo.geo-solutions.it)|51.178.213.8|:443... connected.
WARNING: cannot verify ms-congo.geo-solutions.it's certificate, issued by ‘/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA’:
  Issued certificate has expired.
HTTP request sent, awaiting response... 404 Not Found
2020-08-31 21:31:31 ERROR 404: Not Found.

Build step 'Execute shell' marked build as failure
```

**Comment by randomorder** [comment]
should be sorted @chpicone
