### ISSUE TITLE
Content of some menus

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#19]
The bottom part of the left side panel (in the main page and in the mapview page) must contain some items .
This items and the relative subitems must be loaded dynamically from a configuration JSON file:

![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/b98a5215-6f24-4ee9-bb35-c56628294b1d)

An example of configuration could be:

```
[
{
   name: “Documents”
   items:[
    {name: “doc1”, link: “http://xxx/yyy/doc1”},
    {name: “doc2”, link: “http://xxx/yyy/doc2”}
   ]
},{
   name: “Videos”
   items:[
    {name: “video1”, link: “http://xxx/yyy/video1”},
    {name: “video2”, link: “http://xxx/yyy/video2”}
   ]
}
]
```

With this example the bottom part of the left side panel should be like:
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/64032a8b-4b1c-4ee0-9042-ee8e75bd7a4a)

**Comment by chpicone** [comment]
We need to move this configuration in a static folder to avoid the customer to rebuild the application for any changes.

**Comment by myrdstom** [comment]
Created a server-client type solution for this with a python-flask serevr serving the json data. IT works but we would have to host the python server. This is an option we could consider

**Comment by chpicone** [comment]
@myrdstom we cannot use a python server.
I think one of the following solutions:

- make the build process (at the end) able to put the JSON config file in a static folder (for example the same where the other js script are built) and so fetch it as you know
- otherwise we have to write a Java Servlet library and add it in the web/lib of the server component of mapstore and add the serveltmaping tag to configure the URL endpoint

**Comment by myrdstom** [comment]
I can easily work on the first bullet point. The tricky bit though is writing the Java Servlet Library. I will probably have to do a lot of reading on this as I am unfamiliar with Java

**Comment by chpicone** [comment]
@myrdstom the first one is the best also for me! Go ahead with the first proposed solution
