### ISSUE TITLE
Initialize MapStore project

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#2]
The usual MapStore Project support can be provided for this.
Documentation is available [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-projects/).
I would suggest @MV88 to record the preparation of the project (e.g. using zoom) and to show it to other collegue involved in the project.

**Comment by chpicone** [comment]
The MapStore WebGIS will entirelly replace the WebGIS currently used for the UNREDD portal without replicating functionalities of the current portal that may be missing in MapStore or that are working in a different way.

**Comment by tdipisa** [comment]
@chpicone the procedure to create a MS project is already documented [here](https://mapstore.readthedocs.io/en/latest/developer-guide/project-creation-script/). We could ask to @MV88 to simply check if it is up to date and update it if needed. Let's decide then if assign the task to another resource or let @MV88 do this.

**Comment by chpicone** [comment]
@MV88 as discussed yesterday with @tdipisa you can start with the activity today checking about the correctness of the actual documentation. Please, take note of any changes to be made to the documentation and if these are not many (as we assume) proceed with the relative update.

**Comment by chpicone** [comment]
@MV88 can we consider this issue closed?
