### ISSUE TITLE
Customization of the TOC

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#4]
This means having a different TOC plugin with a different presentation and organizations of layers and groups not using a tree representation but a gallery view with a card for each layer organized in categories (groups). 
Each layer card can have its own thumbnail and the usual TOC functionalities in MapStore need to be maintained.	

This is a complete customization of the TOC component that shall be provided inside the client's MapStore project and not as part of the MapStore core. 
This means that additional effort may be needed to maintain this customization across different versions of MapStore in the future.

**Comment by simboss** [comment]
@chpicone can you try to work on this yourself?

**Comment by chpicone** [comment]
Yes @simboss. Idea is to prepare some draft image to discuss internally (about the feasibility/complexity to use in MapStore) and then to share with the customer.
I have created 2 mockups to discuss internally:
- it provides only a hierarchical level. Each groups at the first level can contains levels in a grid 3 rows x N cols. Levels are shown as a square image (thumbnail). The image mockup is available [here](https://drive.google.com/file/d/1TA4hyRXHVtqxbMN9qgz7AgTZCIm3NPVX/view?usp=sharing)
- it provides a complete organization of groups and levels with not hierarchical levels limitations. Each groups can contains both levels and groups. Groups inside another groups are shown as a sqaure with the name of the group (no thumbnail). When the users navigate in a group inside another group the header (rectangular) section of the group contains a navigation breadcrump (to be able to change the current group visualization and mode to another group in the hierarchy. The image mockup is available [here](https://drive.google.com/file/d/1ga5haFESpkUIXIb0OdkntD87evKU1MPb/view?usp=sharing)

**Comment by chpicone** [comment]
We received their proposal about the TOC [here](https://drive.google.com/file/d/1lWbhGWig9SMJfBmTqQi4oZZpplvfKVfj/view?usp=sharing)

**Comment by chpicone** [comment]
We received their proposal about the TOC [here](https://drive.google.com/file/d/1lWbhGWig9SMJfBmTqQi4oZZpplvfKVfj/view?usp=sharing)
