### ISSUE TITLE
Header in the MapView page is under the map

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#40]
Using a smartphone the header in the MapView page is covered by the map

**Comment by dsuren1** [comment]
Hi @chpicone ,
I couldn't reproduce this issue, when tried with the emulator (with various mobile devices). Kindly let me know the mobile device and browser used, should help narrow the issue down?
![2020-10-12 10_51_07-MapStore 2 project for FAO - Democratic Republic of the Congo](https://user-images.githubusercontent.com/26929983/95708075-fae73f80-0c78-11eb-8e37-844b837814a4.jpg)

**Comment by chpicone** [comment]
@dsuren1 I used emultaor too and it works properly, but using my smartphone (android) with chrome I have reproduced the issue of the customer.

**Comment by chpicone** [comment]
I also tried (right now) using a lenovo tablet (android) with chrome... same problem.
Tha map is over the header (or the header is under the map).

**Comment by chpicone** [comment]
![image](https://user-images.githubusercontent.com/2872823/95829648-cd60cb80-0d36-11eb-8eb6-bb160299bbed.png)
