### ISSUE TITLE
Create a mockup for the custom TOC

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#6]
We need to create some mockups for the customization of the TOC to propose to the customer

**Comment by chpicone** [comment]
Idea is to prepare some draft image to discuss internally (about the feasibility/complexity to use in MapStore) and then to share with the customer.
I have created 2 mockups to discuss internally:

- it provides only a hierarchical level. Each groups at the first level can contains levels in a grid 3 rows x N cols. Levels are shown as a square image (thumbnail). The image mockup is available [here](https://drive.google.com/file/d/1TA4hyRXHVtqxbMN9qgz7AgTZCIm3NPVX/view?usp=sharing)
- it provides a complete organization of groups and levels with not hierarchical levels limitations. Each groups can contains both levels and groups. Groups inside another groups are shown as a sqaure with the name of the group (no thumbnail). When the users navigate in a group inside another group the header (rectangular) section of the group contains a navigation breadcrump (to be able to change the current group visualization and mode to another group in the hierarchy. The image mockup is available [here](https://drive.google.com/file/d/1ga5haFESpkUIXIb0OdkntD87evKU1MPb/view?usp=sharing)

We want to mantain all the current properties of the TOC and change just the GUI.
I think the only new property to manage is the thumbnail URL for the layers.

**Comment by chpicone** [comment]
@allyoucanmap can you take a quick look at the 2 mockups made?
I think the second one is more compatible with the actual configuration (json) of the TOC.

**Comment by chpicone** [comment]
We will proceed with the simple solution (just one level group of the hierarchy).

**Comment by tdipisa** [comment]
@chpicone the first option is the best one for this in my opinion. We shouldn't make complicated things considering the original requirement: if you want a more hierarchical TOC you have to use the current one (organized as a tree). Anyway we should sent an email to the client to share the solution we have in mind.

**Comment by chpicone** [comment]
@tdipisa I agree with you. I'll write an email to the customer with our proposal and remember him to provide us material for the theme.

**Comment by chpicone** [comment]
@tdipisa I have prepared a [document ](https://docs.google.com/document/d/1nHaj15VVEKHAJ_E-41moKIf6tJkyMUUqtHtwi6mOfvc/edit?usp=sharing)with our proposal for the TOC
