### ISSUE TITLE
Legend in a popup

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#74]
Customer is asking to add a new button in the toolbar section of the layer for the legend.
When the user move the cursor "over" this button (afther some time... maybe 1 sec) a popup panel has to appear showing the image of the legend (from GetLegend request):
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/69f3d759-2e18-40c6-af8c-6edb9e4f40fa)
When the user move the cursor "out" this button the panel has to disappear.

We can decide to fix the size of this panel (eg. in height) but preserving the ration height/width of the image.
The user can click the legend to open a new tab with the original image of the legend.

**Comment by dsuren1** [comment]
@chpicone 
> I. When the user move the cursor "out" this button the panel has to disappear.
> 
> II. The user can click the legend to open a new tab with the original image of the legend.

As soon as, the users moves away, the legend will disappear (**I**), this will prevent user from performing **II**/second requirement suggested. Kindly clarify. Thanks

**Comment by chpicone** [comment]
@dsuren1, you right. 
So I think better to open the window explicitly when the user click the "legend" button.
We can put a close icon button to make the user able to close the window.

**Comment by chpicone** [comment]
> II. The user can click the legend to open a new tab with the original image of the legend.
@dsuren1 I think the item II is missing:

**Comment by dsuren1** [comment]
> > II. The user can click the legend to open a new tab with the original image* of the legend.
> 
> (*original image size)
> 
> @dsuren1 I think the item II is missing

This PR addresses it https://github.com/geosolutions-it/MapStore2-C013/issues/82
