### ISSUE TITLE
Update dynamic menu in the home page

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C013#76]
We have to change the current configuration (customMenuItems.json) of sub-menus in the burger menu of the home page in this way:
- Links
  - Documents
  - Videos
  - Actualities
  - Tutorials

**Comment by chpicone** [comment]
This is the required menu:
![image](https://user-images.githubusercontent.com/2872823/114554444-04248980-9c67-11eb-854b-53b55de918e2.png)
To update this it was necessary to change the file [menuConfig.js](https://github.com/geosolutions-it/MapStore2-C013/blob/master/js/menuConfig/menuConfig.js).
But when we build and deploy it we can see it correctly in the home page but in the mapview page we have a different one:
![image](https://user-images.githubusercontent.com/2872823/114554804-63829980-9c67-11eb-8e76-d067266dbdd3.png)

For some reason we are looking in 2 different configuration files.

please @dsuren1, can you take a look?

**Comment by chpicone** [comment]
@dsuren1: also in the mapview page the custom menu it is not translated (but before this it is necessary to make this menu using the same config file used in the home page).

**Comment by dsuren1** [comment]
@chpicone Sure, I will look into it
